use_frameworks!

target 'PrivateLibTest_Example' do
  pod 'PrivateLibTest', :path => '../'

  target 'PrivateLibTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
